name: Generate Snake
on:
  schedule: # 每12小时自动更新动图
    - cron: "0 */12 * * *"
  workflow_dispatch: # 支持手动触发
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
      - name: Push SVG到output分支
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
